# Generated by Django 5.2.4 on 2025-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_project_projectcategory_projectimage_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='type',
            new_name='contact_type',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
